In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,7,"sudh" , 34.565, True]

In [9]:
a1 = np.array(l1)

In [10]:
a2 = np.array([[1,2,3] , [4,5,6]])

In [12]:
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9]]])

In [13]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
a1.ndim

1

In [17]:
a2.ndim

2

In [19]:
a3.ndim

3

In [20]:
a1.size

7

In [21]:
a2.size

6

In [22]:
a3.size

9

In [23]:
a1.shape

(7,)

In [24]:
a2.shape

(2, 3)

In [25]:
a3.shape

(1, 3, 3)

In [26]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [27]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [40]:
np.random.randint(2,50 ,(3,4) )

array([[ 6, 23, 20, 46],
       [14, 30, 19, 25],
       [ 6,  5,  3, 49]])

In [41]:
np.random.randint(2,50 ,(2,3,4) )

array([[[31, 14, 41, 45],
        [16, 30, 44,  7],
        [38, 30, 10,  7]],

       [[19,  7, 43, 21],
        [28,  9, 43, 30],
        [34, 44, 40, 42]]])

In [45]:
np.random.rand(5,4)

array([[0.30453833, 0.91056161, 0.21440296, 0.53983438],
       [0.5015424 , 0.7478575 , 0.80669438, 0.34134798],
       [0.09348307, 0.29379957, 0.64010475, 0.90672249],
       [0.18514031, 0.08344503, 0.74298752, 0.16580552],
       [0.89126883, 0.56665101, 0.7111257 , 0.20834303]])

In [47]:
a4 =  np.random.randn(4,4)

In [48]:
a4

array([[ 0.19822874,  1.79885295, -0.74235958, -0.10246964],
       [-0.52587848,  0.52904912, -1.30771402,  1.40359366],
       [ 0.51919846,  1.15850157,  1.41179019,  0.5011404 ],
       [ 1.21982183, -2.43946612,  0.10028469, -0.66612944]])

In [50]:
a4.reshape(2,8)

array([[ 0.19822874,  1.79885295, -0.74235958, -0.10246964, -0.52587848,
         0.52904912, -1.30771402,  1.40359366],
       [ 0.51919846,  1.15850157,  1.41179019,  0.5011404 ,  1.21982183,
        -2.43946612,  0.10028469, -0.66612944]])

In [51]:
a4.reshape(8,2)

array([[ 0.19822874,  1.79885295],
       [-0.74235958, -0.10246964],
       [-0.52587848,  0.52904912],
       [-1.30771402,  1.40359366],
       [ 0.51919846,  1.15850157],
       [ 1.41179019,  0.5011404 ],
       [ 1.21982183, -2.43946612],
       [ 0.10028469, -0.66612944]])

In [52]:
a4.reshape(16,1)

array([[ 0.19822874],
       [ 1.79885295],
       [-0.74235958],
       [-0.10246964],
       [-0.52587848],
       [ 0.52904912],
       [-1.30771402],
       [ 1.40359366],
       [ 0.51919846],
       [ 1.15850157],
       [ 1.41179019],
       [ 0.5011404 ],
       [ 1.21982183],
       [-2.43946612],
       [ 0.10028469],
       [-0.66612944]])

In [54]:
a4.reshape(2,-134564364)

array([[ 0.19822874,  1.79885295, -0.74235958, -0.10246964, -0.52587848,
         0.52904912, -1.30771402,  1.40359366],
       [ 0.51919846,  1.15850157,  1.41179019,  0.5011404 ,  1.21982183,
        -2.43946612,  0.10028469, -0.66612944]])

In [56]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[ 0.19822874,  1.79885295, -0.74235958,
                -0.10246964],
               [-0.52587848,  0.52904912, -1.30771402,
                 1.40359366]],

              [[ 0.51919846,  1.15850157,  1.41179019,
                 0.5011404 ],
               [ 1.21982183, -2.43946612,  0.10028469,
                -0.66612944]]]]]]]]]])

In [57]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [58]:
a1[0]

'4'

In [59]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [60]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [61]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [62]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [63]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [67]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [68]:
a2[[0,1] , 1:]

array([[2, 3],
       [5, 6]])

In [71]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [75]:
a5 = np.random.randint(2,90 , (6,5))

In [76]:
a5

array([[41, 11, 26, 78, 73],
       [61, 67, 30,  4, 77],
       [20, 45, 87,  6, 81],
       [ 6, 64, 21, 42, 51],
       [61,  8, 28, 21, 55],
       [36, 51, 62, 66, 23]])

In [77]:
a5[a5>40]

array([41, 78, 73, 61, 67, 77, 45, 87, 81, 64, 42, 51, 61, 55, 51, 62, 66])

In [78]:
a5

array([[41, 11, 26, 78, 73],
       [61, 67, 30,  4, 77],
       [20, 45, 87,  6, 81],
       [ 6, 64, 21, 42, 51],
       [61,  8, 28, 21, 55],
       [36, 51, 62, 66, 23]])

In [80]:
a5[0,1] = 100

In [81]:
a5

array([[ 41, 100,  26,  78,  73],
       [ 61,  67,  30,   4,  77],
       [ 20,  45,  87,   6,  81],
       [  6,  64,  21,  42,  51],
       [ 61,   8,  28,  21,  55],
       [ 36,  51,  62,  66,  23]])

In [87]:
a6 = np.random.randint(0,3 , (3,3))

In [88]:
a7 = np.random.randint(0,3 , (3,3))

In [89]:
a6

array([[0, 1, 0],
       [0, 1, 2],
       [0, 0, 1]])

In [90]:
a7



array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]])

In [91]:
a6*a7

array([[0, 2, 0],
       [0, 2, 0],
       [0, 0, 0]])

In [92]:
a6@a7

array([[1, 2, 0],
       [3, 6, 0],
       [1, 2, 0]])

In [93]:
a6

array([[0, 1, 0],
       [0, 1, 2],
       [0, 0, 1]])

In [94]:
a6+100

array([[100, 101, 100],
       [100, 101, 102],
       [100, 100, 101]])

In [95]:
a6*2

array([[0, 2, 0],
       [0, 2, 4],
       [0, 0, 2]])

In [96]:
a6/0

C:\Users\win10\AppData\Local\Temp\ipykernel_22484\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\win10\AppData\Local\Temp\ipykernel_22484\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, inf, nan],
       [nan, inf, inf],
       [nan, nan, inf]])

In [97]:
a6

array([[0, 1, 0],
       [0, 1, 2],
       [0, 0, 1]])

In [98]:
a6**3


array([[0, 1, 0],
       [0, 1, 8],
       [0, 0, 1]], dtype=int32)

In [100]:
a8 = np.zeros((4,4))

In [101]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [103]:
a9  = np.ones((4,5))

In [104]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [106]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [107]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [110]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [114]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [116]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [118]:
a6.T

array([[0, 0, 0],
       [1, 1, 0],
       [0, 2, 1]])

In [119]:
a6

array([[0, 1, 0],
       [0, 1, 2],
       [0, 0, 1]])

In [120]:
a5

array([[ 41, 100,  26,  78,  73],
       [ 61,  67,  30,   4,  77],
       [ 20,  45,  87,   6,  81],
       [  6,  64,  21,  42,  51],
       [ 61,   8,  28,  21,  55],
       [ 36,  51,  62,  66,  23]])

In [121]:
np.sqrt(a5)

array([[ 6.40312424, 10.        ,  5.09901951,  8.83176087,  8.54400375],
       [ 7.81024968,  8.18535277,  5.47722558,  2.        ,  8.77496439],
       [ 4.47213595,  6.70820393,  9.32737905,  2.44948974,  9.        ],
       [ 2.44948974,  8.        ,  4.58257569,  6.4807407 ,  7.14142843],
       [ 7.81024968,  2.82842712,  5.29150262,  4.58257569,  7.41619849],
       [ 6.        ,  7.14142843,  7.87400787,  8.1240384 ,  4.79583152]])

In [122]:
np.exp(a5)

array([[6.39843494e+17, 2.68811714e+43, 1.95729609e+11, 7.49841700e+33,
        5.05239363e+31],
       [3.10429794e+26, 1.25236317e+29, 1.06864746e+13, 5.45981500e+01,
        2.75851345e+33],
       [4.85165195e+08, 3.49342711e+19, 6.07603023e+37, 4.03428793e+02,
        1.50609731e+35],
       [4.03428793e+02, 6.23514908e+27, 1.31881573e+09, 1.73927494e+18,
        1.40934908e+22],
       [3.10429794e+26, 2.98095799e+03, 1.44625706e+12, 1.31881573e+09,
        7.69478527e+23],
       [4.31123155e+15, 1.40934908e+22, 8.43835667e+26, 4.60718663e+28,
        9.74480345e+09]])

In [123]:
np.log10(a5)

array([[1.61278386, 2.        , 1.41497335, 1.8920946 , 1.86332286],
       [1.78532984, 1.8260748 , 1.47712125, 0.60205999, 1.88649073],
       [1.30103   , 1.65321251, 1.93951925, 0.77815125, 1.90848502],
       [0.77815125, 1.80617997, 1.32221929, 1.62324929, 1.70757018],
       [1.78532984, 0.90308999, 1.44715803, 1.32221929, 1.74036269],
       [1.5563025 , 1.70757018, 1.79239169, 1.81954394, 1.36172784]])

In [128]:
list(range(0,10 , 2))

[0, 2, 4, 6, 8]

In [133]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [135]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [136]:
np.logspace(2,4,num=4 , base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [137]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
import cufflinks as cf 
import numpy as np
import pandas as pd 
import seaborn as sns



In [2]:
!pip install cufflinks

  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68724 sha256=df1e8abba65e659daf6fbd39f044d95ed717d8b59fcc4f7dd0b9c64c351f5baf
  Stored in directory: c:\users\kunal\appdata\local\pip\cache\wheels\6b\76\62\6da97734911ffcbdd559fd1a3f28526321f0ae699182a23866
Successfully built cufflinks


In [25]:
cf.go_offline()

In [26]:
df = pd.DataFrame(np.random.randn(100,3),columns=['A' , 'B' ,'C'])

In [27]:
df

A         B         C
0  -1.805174  1.778083  1.996909
1  -0.380986  0.231337  1.202111
2   0.373997 -1.284450 -2.059349
3   1.161488  0.777395  0.859463
4   0.133563 -0.785234 -1.212131
..       ...       ...       ...
95 -2.609768 -0.007388  0.278450
96 -1.095088 -0.061543 -0.769516
97 -0.771593  1.589764 -1.023394
98  0.027921 -0.252924 -0.219546
99 -0.840876 -0.650310  1.115784

[100 rows x 3 columns]

In [28]:
df.iplot()

In [35]:
df0 = pd.DataFrame(np.random.randint(3,100,(100,3)))
df0

0   1   2
0   35  87  31
1   28  85  59
2    6  87  45
3   62  53  88
4   71  98  91
..  ..  ..  ..
95  62  19  49
96  16  20   7
97  59  24  41
98  12   6  92
99  88  30  81

[100 rows x 3 columns]

In [36]:
df0.iplot()

In [11]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [12]:
df1

0
0   10
1   51
2   82
3    4
4   11
..  ..
95  60
96  86
97  16
98  72
99  10

[100 rows x 1 columns]

In [13]:
df1.iplot()

In [14]:
df1

0
0   10
1   51
2   82
3    4
4   11
..  ..
95  60
96  86
97  16
98  72
99  10

[100 rows x 1 columns]

In [15]:
df

A         B         C
0   0.110192 -1.726830 -0.749294
1   0.690647 -1.628649  0.276194
2  -1.837982 -1.601289  0.515326
3  -0.412520  0.217765 -1.189031
4   1.991578 -0.142727 -0.115627
..       ...       ...       ...
95 -0.226456 -0.523578  0.603383
96 -2.508969 -0.927559 -0.788972
97  0.691885  0.413873 -0.268056
98 -0.396917 -0.828516  1.378733
99 -2.457509 -0.046921  1.333435

[100 rows x 3 columns]

In [16]:
df.iplot(x = 'A' , y = 'B',mode = 'markers')

In [17]:
df2 = sns.load_dataset('titanic')

In [18]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [19]:
df2.iplot(x = 'age' , y ='fare',mode = 'markers' )

In [20]:
df2.iplot(x = 'age' , y ='pclass',mode = 'markers' )

In [21]:
df2.iplot(x = 'fare' , y ='pclass',mode = 'markers' )

In [22]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [23]:
df2.iplot(kind = 'bar' , x = 'sex' , y = 'survived')